//const HOME_URL: string = "https://7fa2-195-135-0-87.ngrok-free.app/";
const HOME_URL: string = "http://localhost:3001";
export const PROJECTS_URL: string = `${HOME_URL}/projects`;
export const LABELS_URL: string = `${HOME_URL}/labels`;
export const CRYPTOS_URL: string = `${HOME_URL}/cryptos`;
export const CATEGORIES_URL: string = `${HOME_URL}/categories`;
export const CRITERIONS_URL: string = `${HOME_URL}/criterions`;
export const COMPANY_TYPES_URL: string = `${HOME_URL}/companyTypes`;
export const COMPANIES_URL: string = `${HOME_URL}/companies`;